spring.application.name=example-01-email-login
server.port=${SERVER_PORT:8088}
spring.datasource.url=${DB_URL:jdbc:h2:mem:email_login;MODE=MSSQLServer;DB_CLOSE_DELAY=-1}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:create-drop}
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.thymeleaf.cache=false
spring.config.import=optional:file:.env[.properties]
